apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster-user-code
  namespace: odp-dagster
  labels:
    app: dagster-user-code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dagster-user-code
  template:
    metadata:
      labels:
        app: dagster-user-code
    spec:
      serviceAccountName: dagster-task-ksa
      containers:
      - name: user-code
        image: asia-northeast1-docker.pkg.dev/olist-data-portal/odp-dagster/dagster-user-code:latest
        ports:
        - containerPort: 4000
          name: http
        env:
        - name: DAGSTER_CURRENT_IMAGE
          value: "asia-northeast1-docker.pkg.dev/olist-data-portal/odp-dagster/dagster-user-code:latest"
        - name: KAGGLE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: odp-kaggle-api-token
              key: token
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi

