FROM --platform=linux/amd64 python:3.12-slim

RUN pip install --no-cache-dir \
    dagster \
    dagster-webserver \
    dagster-cloud \
    dagster-postgres \
    python-dateutil

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster_project/dagster_project/dagster.yaml $DAGSTER_HOME/
COPY dagster_project/dagster_project/workspace.yaml $DAGSTER_HOME/workspace.yaml
COPY dagster_project/dagster_project/startup.sh /usr/local/bin/startup.sh
RUN chmod +x /usr/local/bin/startup.sh

WORKDIR $DAGSTER_HOME

# webserverがリッスンするポートを公開
EXPOSE 3000

# startup.shをエントリーポイントとして設定
# これにより、すべてのコマンドがstartup.shを経由して実行され、
# 環境変数の置き換えが確実に行われる
ENTRYPOINT ["/usr/local/bin/startup.sh"]
