FROM --platform=linux/amd64 python:3.12-slim

RUN pip install --no-cache-dir dagster

WORKDIR /opt/dagster/app

COPY dagster_project/dagster_project/__init__.py ./dagster_project/
COPY dagster_project/dagster_project/definitions.py ./dagster_project/

ENV PYTHONPATH=/opt/dagster/app

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-m", "dagster_project.definitions"]
